name = ""
main = "src/index.js"
compatibility_date = "2024-03-{}"
[ai]
binding = "AI"
[[vectorize]]
binding = "VECTORIZE_INDEX"
index_name = ""
[[d1_databases]]
binding = "DB"
database_name = ""
database_id = ""